"""
DFR-Forensics - Générateur de Rapport d'Expertise Judiciaire
Génère un rapport formel d'investigation en Markdown et HTML (avec impression PDF)
contenant les hashes cryptographiques (SHA-256 / MD5), la géométrie et la preuve de restauration.
"""

import os
import hashlib
from typing import Dict, Any
from core.image_reader import ForensicImageReader
from core.scanner import ScanDiagnostic
from core.i18n import get_lang


class ForensicReportGenerator:
    """Générateur de rapports d'expertise médico-légale."""

    def __init__(self, reader: ForensicImageReader, diag: ScanDiagnostic):
        self.reader = reader
        self.diag = diag
        self.hashes: Dict[str, str] = {}

    def compute_fast_hashes(self, sample_mb: int = 10) -> Dict[str, str]:
        """Calcule les empreintes MD5 et SHA-256 (sur les premiers et derniers Mo pour rapidité)."""
        md5 = hashlib.md5()
        sha256 = hashlib.sha256()

        sample_bytes = min(sample_mb * 1024 * 1024, self.reader.total_size_bytes)
        # Échantillon début
        chunk_start = self.reader.read_bytes(0, sample_bytes // 2)
        # Échantillon fin
        end_offset = max(0, self.reader.total_size_bytes - sample_bytes // 2)
        chunk_end = self.reader.read_bytes(end_offset, sample_bytes // 2)

        data = chunk_start + chunk_end
        md5.update(data)
        sha256.update(data)

        self.hashes = {
            "md5_sample": md5.hexdigest(),
            "sha256_sample": sha256.hexdigest(),
        }
        return self.hashes

    def generate_markdown_report(self, lang: str = "fr") -> str:
        if not self.hashes:
            self.compute_fast_hashes()

        fname = os.path.basename(self.reader.path)
        size_gib = self.reader.total_size_bytes / (1024**3)
        tot_sec = self.reader.total_sectors

        profile_text = self.diag.wiper_profile.get(lang, "N/A") if hasattr(self.diag, "wiper_profile") else "N/A"

        if lang == "en":
            report = f"""# FORENSIC INVESTIGATION REPORT - PARTITION & DISK TRIAGE
**Generated by DFR-Forensics Suite**
**Classification:** TLP:CLEAR / Legal Evidence

---

## 1. EVIDENCE CONTAINER IDENTIFICATION
* **Evidence File:** `{fname}`
* **Full Path:** `{self.reader.path}`
* **Container Size:** {size_gib:.4f} GiB ({self.reader.total_size_bytes:,} bytes)
* **Total Sector Count:** {tot_sec:,} (Logical sector size: {self.reader.sector_size} bytes)
* **Cryptographic Integrity Hash (Sample MD5):** `{self.hashes.get('md5_sample')}`
* **Cryptographic Integrity Hash (Sample SHA-256):** `{self.hashes.get('sha256_sample')}`

---

## 2. INCIDENT & ATTACK PROFILING
* **Suspected Attack Profile:** **{profile_text}**
* **Initial Wipe Frontier:** LBA {self.diag.wipe_frontier_lba or 0:,} ({(self.diag.wiped_bytes or 0)/(1024*1024):.2f} MB zeroed)
* **Overall Status:** {self.diag.status_summary}

---

## 3. UEFI METADATA HEALTH & TRIAGE
* **Protective MBR (LBA 0):** {'VALID (0xEE)' if self.diag.mbr_valid else ('DESTROYED (100% ZEROS)' if self.diag.mbr_is_all_zero else 'INVALID')}
* **Primary GPT Header (LBA 1):** {'INTACT' if self.diag.primary_gpt_valid_crc else 'DESTROYED / WIPED'}
* **Backup GPT Header (LBA -1):** {'INTACT (VALID CRC32)' if self.diag.backup_gpt_valid_crc else 'MISSING / CORRUPT'}

---

## 4. DETECTED RECOVERABLE PARTITIONS
| # | Partition Name | Filesystem / Signature | Start LBA | End LBA | Size | Type GUID |
|---|----------------|------------------------|-----------|---------|------|-----------|
"""
            for idx, p in enumerate(self.diag.partitions, 1):
                sz_mb = (p.total_sectors * self.reader.sector_size) / (1024 * 1024)
                sz_str = f"{sz_mb/1024:.2f} GiB" if sz_mb >= 1024 else f"{sz_mb:.2f} MiB"
                report += f"| {idx} | {p.name or 'Partition'} | {p.detected_fs or p.type_name} | {p.first_lba:,} | {p.last_lba:,} | {sz_str} | `{p.type_guid}` |\n"

            report += f"""
---

## 5. TECHNICAL RECONSTRUCTION METHODOLOGY
1. **Protective MBR Generation:** Standard LBA 0 sector with 0xAA55 signature and type 0xEE covering full sector count.
2. **Primary Header Synthesis:** Swapped CurrentLBA (1) and BackupLBA ({tot_sec - 1}). Recalculated official UEFI CRC32 with zeroed checksum field.
3. **Partition Table Restoration:** Replicated 128-entry array from LBA -33 to LBA 2..33.

---
*Report certified by DFR-Forensics Suite.*
"""

        else:
            report = f"""# RAPPORT D'EXPERTISE FORENSIQUE - TRIAGE & RESTAURATION DE DISQUE
**Généré par la suite logicielle DFR-Forensics**
**Classification :** TLP:CLEAR / Pièce à Conviction

---

## 1. IDENTIFICATION DU CONTENEUR DE PREUVE
* **Fichier analysé :** `{fname}`
* **Chemin absolu :** `{self.reader.path}`
* **Taille physique :** {size_gib:.4f} Gio ({self.reader.total_size_bytes:,} octets)
* **Nombre total de secteurs :** {tot_sec:,} (Taille de secteur logique : {self.reader.sector_size} octets)
* **Empreinte d'intégrité (Échantillon MD5) :** `{self.hashes.get('md5_sample')}`
* **Empreinte d'intégrité (Échantillon SHA-256) :** `{self.hashes.get('sha256_sample')}`

---

## 2. PROFILAGE DE L'ATTAQUE (WIPER / RANSOMWARE)
* **Profil suspecté :** **{profile_text}**
* **Frontière du wipe initial :** LBA {self.diag.wipe_frontier_lba or 0:,} ({(self.diag.wiped_bytes or 0)/(1024*1024):.2f} Mo écrasés)
* **Diagnostic global :** {self.diag.status_summary}

---

## 3. SANTÉ ET INTÉGRITÉ DES STRUCTURES UEFI
* **Protective MBR (LBA 0) :** {'VALIDE (0xEE)' if self.diag.mbr_valid else ('DÉTRUIT (100% ZÉROS)' if self.diag.mbr_is_all_zero else 'INVALIDE')}
* **Table GPT Primaire (LBA 1) :** {'INTACTE' if self.diag.primary_gpt_valid_crc else 'DÉTRUITE / WIPÉE'}
* **Table GPT de Secours (LBA -1) :** {'INTACTE (CRC32 VALIDE)' if self.diag.backup_gpt_valid_crc else 'ABSENTE / CORROMPUE'}

---

## 4. PARTITIONS DÉTECTÉES ET RÉCUPÉRABLES
| # | Nom Partition | Système / Signature | LBA Début | LBA Fin | Taille | GUID Type |
|---|---------------|---------------------|-----------|---------|--------|-----------|
"""
            for idx, p in enumerate(self.diag.partitions, 1):
                sz_mb = (p.total_sectors * self.reader.sector_size) / (1024 * 1024)
                sz_str = f"{sz_mb/1024:.2f} Gio" if sz_mb >= 1024 else f"{sz_mb:.2f} Mio"
                report += f"| {idx} | {p.name or 'Partition'} | {p.detected_fs or p.type_name} | {p.first_lba:,} | {p.last_lba:,} | {sz_str} | `{p.type_guid}` |\n"

            report += f"""
---

## 5. MÉTHODOLOGIE TECHNIQUE DE RESTAURATION
1. **Création du Protective MBR :** Génération à LBA 0 avec signature 0xAA55 et partition unique 0xEE couvrant l'ensemble du média.
2. **Reconstitution du Header Primaire :** Inversion des adresses LBA (CurrentLBA = 1, BackupLBA = {tot_sec - 1}). Recalcul de la somme de contrôle CRC32 UEFI.
3. **Réplication du Tableau de Partitions :** Copie conforme des 128 entrées depuis LBA -33 vers LBA 2..33.

---
*Rapport d'expertise certifié conforme par DFR-Forensics.*
"""

        return report
